name: Wine-workflow
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - uses: iterative/setup-cml@v1
      
      - name: Train model
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub Actions
        run: |
          # Your ML workflow goes here
          python train.py
          
          # Create the report
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data Viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          # Use cml comment instead of cml-send-comment
          cml comment create report.md
